# Generated by Django 4.0.2 on 2022-04-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_admin_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_profile',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
