# Generated by Django 4.0.2 on 2022-04-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('registration_date', models.DateField()),
                ('roll_no', models.CharField(max_length=1000)),
                ('sub_class', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_mobile', models.IntegerField()),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
