# Generated by Django 4.0.2 on 2022-04-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
